### ISSUE TITLE
Concern regards to Row/Record Size (maximum bytes per record): its for the Capacity Plan. Chapter 4

### ISSUE THREAD

**Issue by ralch34** [philrhoy/IMCCVenueReservationSystem2023#73]
Question 1:  where can I find each byte size for each attribute in a selected table? 
(I tried looking in localhost phpmyadmin. It just shows the current size of stored records from the table.)

![Screenshot_54](https://github.com/philrhoy/IMCCVenueReservationSystem2023/assets/90671718/70633d57-8979-4e7b-b80c-f7cb6b9d6d8d)

Question 2:  in terms of practical use, is varchar(255) too big?  
also, how much byte size does the data type "datetime" have?
how much byte size does the data type "text" have? from columns "description and notes" in schedules?

Question 3:  for the "act_form_file" and "letter_approve_file", I heard that longblob or longtext are datatype commonly used for larger file store. Why both columns are in "varchar"? 

![Screenshot_50](https://github.com/philrhoy/IMCCVenueReservationSystem2023/assets/90671718/3068f2e2-984f-47a2-96ee-6397d40e1d96)
![Screenshot_51](https://github.com/philrhoy/IMCCVenueReservationSystem2023/assets/90671718/5a61f784-ef3d-4fc2-9964-0ed48ad53fc2)
![Screenshot_52](https://github.com/philrhoy/IMCCVenueReservationSystem2023/assets/90671718/5c7ec15e-3484-4587-a183-82b8603cd80c)
![Screenshot_53](https://github.com/philrhoy/IMCCVenueReservationSystem2023/assets/90671718/743a3dbb-9db3-43f5-b8bd-9b828895f937)

**Comment by philrhoy** [comment]
Q1: You can refer here for the total byte size per column in the table.
https://dev.mysql.com/doc/refman/8.0/en/string-type-syntax.html#:~:text=MySQL%20stores%20VARCHAR%20values%20as,require%20more%20than%20255%20bytes.

Q2: If it is not good for 255, then what is your recommended character size for an unpredictable value to be inputted by the user?

Q3: We don't digitally save the images on the database due to the need for conversion when we are going to save them as blob data. We stored the images and files in the system's file folder, named "uploads."

**Comment by ralch34** [comment]
answers received
